feedback/urls.py
from django.conf.urls import url
from feedback import views


urlpatterns = [
    # url(r'^$', views.feedback_list),
    # url(r'(?P<pk>[0-9]+)/$', views.feedback_detail),
    url(r'^$', views.FeedbackView.as_view(), name='feedback'),
]

gvis_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from pages.views import ClickView, MetaView, VersionView

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^$', TemplateView.as_view(template_name='pages/index.html'), name='index'),
    url(r'^download/$', TemplateView.as_view(template_name='pages/download.html'), name='download'),
    url(r'^gallery/$', 'pages.views.gallery', name='gallery'),
    url(r'^ajax/', include([
        url(r'^click/$', ClickView.as_view()),
        url(r'^usermeta/$', MetaView.as_view()),
    ])),
    url(r'^version/$', VersionView.as_view()),
]

feedback/models.py
from django.db import models


class Feedback(models.Model):
    feedback_text = models.CharField(verbose_name="Текст сообщения", max_length=5000)
    author_name = models.CharField(verbose_name="Имя автора", max_length=100, blank=True)
    author_email = models.EmailField(verbose_name="Почтовый адрес автора", max_length=100, blank=True)
    sending_date = models.DateTimeField(verbose_name="Дата отправки", auto_now_add=True)

    def __str__(self):
        return self.feedback_text

pages/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

OS_TYPE_CHOICES = (
    ('WIN', 'Windows'),
    ('LIN', 'Linux'),
)


class GvisDownloadLink(models.Model):
    download_url = models.URLField(blank=False)
    os_type = models.CharField(choices=OS_TYPE_CHOICES, max_length=3, blank=False, default=OS_TYPE_CHOICES[0][0])
    release_date = models.DateTimeField(default=timezone.now, blank=False)
    version_major = models.PositiveSmallIntegerField(blank=False)
    version_minor = models.PositiveSmallIntegerField(blank=False)
    version_patch = models.PositiveSmallIntegerField(blank=False)
    version_description = RichTextField(blank=False)
    display = models.BooleanField(default=True)

    def __str__(self):
        return "ver. {}.{}.{}, {}".format(self.version_major, self.version_minor, self.version_patch,
                                                dict(OS_TYPE_CHOICES).get(self.os_type))

    def get_version(self):
        return "{}.{}.{}".format(self.version_major, self.version_minor, self.version_patch)


class Visitor(models.Model):
    ip = models.GenericIPAddressField(blank=True, null=True)
    user_agent = models.CharField(max_length=1024, blank=True)

    def __str__(self):
        return str(self.ip)



class LinkClick(models.Model):
    link = models.ForeignKey(GvisDownloadLink)
    visitor = models.ForeignKey(Visitor)
    click_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} clicked on {}".format(str(self.visitor), str(self.link))


class VideoExample(models.Model):
    title = models.CharField(verbose_name="Название", max_length=200)
    video_id = models.CharField(verbose_name="ID видео", max_length=20)
    description = models.CharField(verbose_name="Описание", max_length=1000)
    data_url = models.URLField(verbose_name="Ссылка на данные")

    def __str__(self):
        return str(self.title)

feedback/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from feedback.models import Feedback
from feedback.serializers import FeedbackSerializer
from django.views.generic import TemplateView
from django.shortcuts import render
from django.forms import ModelForm, Textarea
from django.utils.decorators import method_decorator


class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedback_text', 'author_name', 'author_email']
        widgets = {
            'feedback_text': Textarea(attrs={'cols': 40, 'rows': 10}),
        }
        labels = {
            'feedback_text': '* Текст сообщения',
            'author_name': 'Ваше имя',
            'author_email': 'Адрес почты для обратной связи',
        }


class FeedbackView(TemplateView):
    template_name = 'feedback/feedback.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = FeedbackForm()
        return render(request, template_name=self.template_name, context={'form': form})

    def post(self, request, *args, **kwargs):
        if request.META['CONTENT_TYPE'] == 'application/json':
            data = JSONParser().parse(request)
            serializer = FeedbackSerializer(data=data)
            if serializer.is_valid():
                serializer.save()
                return JSONResponse(serializer.data, status=201)
            return JSONResponse(serializer.errors, status=400)
        else:
            form = FeedbackForm(request.POST)
            if form.is_valid():
                form.save()
                return render(request, template_name=self.template_name)
            else:
                return render(request, template_name=self.template_name, context={'form': form})

pages/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from .models import Visitor, LinkClick, GvisDownloadLink, VideoExample
from django.shortcuts import render


class ClickView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        print("GET click captured in server")
        print("REMOTE_ADDR: " + request.META['REMOTE_ADDR'])
        print("HTTP_USER_AGENT: " + request.META['HTTP_USER_AGENT'])
        return HttpResponse(content="GET OK", content_type="text/plain")

    def post(self, request, *args, **kwargs):
        print("POST click captured in server")
        print(request.POST)
        try:
            visitor = Visitor(ip=request.POST['REMOTE_ADDR'], user_agent = request.POST['HTTP_USER_AGENT'])
            visitor.save()
            link = GvisDownloadLink.objects.get(download_url__exact=request.POST['download_url'])
            click = LinkClick(link=link, visitor=visitor)
            click.save()
            return HttpResponse(content="POST OK", content_type="text/plain")
        except Exception as ex:
            print("!!!!!!! " + str(ex))


class MetaView(View):
    def get(self, request, *args, **kwargs):
        print("metaview")
        meta = {
            'HTTP_USER_AGENT': request.META['HTTP_USER_AGENT'],
            'REMOTE_ADDR': request.META['REMOTE_ADDR'],
        }
        return JsonResponse(meta)


class VersionView(View):
    def get(self, request, *args, **kwargs):
        last_version = ''
        version = GvisDownloadLink.objects.filter(display=True).order_by('-version_major', '-version_minor', '-version_patch')[:1]
        if version:
            last_version = version[0].get_version()
        response = {
            'last_version': last_version,
            'download_url':  ("http://" + request.get_host() + '/' + "download/"),
        }
        return JsonResponse(response)


def gallery(request):
    examples = VideoExample.objects.all()
    return render(request, 'pages/gallery.html', {'examples': examples})

feedback/templates/feedback/feedback.html
{% extends 'pages/base.html' %}
{% load staticfiles page_tags %}

{% block title %}Написать - {{ block.super }}{% endblock %}

{% block main %}
<form class="feedback" action="{% url 'feedback' %}" method="post">
    {% if form %}
        {% if form.feedback_text.errors %}
            <ul class="errorlist">
                {% for error in form.feedback_text.errors %}
                    <li>Текст сообщения: {{ error|lower }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <p>{{ form.feedback_text.label_tag }}<br>
        {{ form.feedback_text }}</p>

        {% if form.author_name.errors %}
            <ul class="errorlist">
                {% for error in form.author_name.errors %}
                    <li>Ваше имя: {{ error|lower }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <p>{{ form.author_name.label_tag }}<br>
        {{ form.author_name }}</p>

        {% if form.author_email.errors %}
            <ul class="errorlist">
                {% for error in form.author_email.errors %}
                    <li>Адрес почты: {{ error|lower }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <p>{{ form.author_email.label_tag }}<br>
        {{ form.author_email }}</p>
        <p><input type="submit" value="Отправить"></p>
        <p class="note">* обязательно к заполнению</p>
    {% else %}
        <div class="complete">&#10004;</div>
        <p class="thankyou">Спасибо за ваш отзыв!</p>
    {% endif %}
</form>
{% endblock %}

pages/templates/pages/base.html
{% load static compress %}<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	{# <meta name="viewport" content="width=device-width, initial-scale=1.0"> #}
	<title>{% block title %}Gvis{% endblock %}</title>
	<link rel="shortcut icon" href="{% static 'pages/favicon.ico' %}" type="image/x-icon">
	<link rel="stylesheet" href="http://yastatic.net/bootstrap/3.3.4/css/bootstrap.min.css">
	{% compress css %}
		<link rel="stylesheet" href="{% static 'pages/css/style.css' %}" type="text/css" charset="utf-8">
	{% endcompress %}
</head>
<body>
	<div class="container">
		<header class="page-header">
			<div class="row">
				<div class="logo">
					<a href="/"><img alt="Gvis" width="175" height="175" src="{% static 'pages/img/logo.png' %}"></a>
				</div>
				<div class="col-xs-8">
					<h1>Gvis</h1>
					<h2>Программный комплекс для визуализации нестационарных течений</h2>
				</div>
			</div>
			<nav class="site-menu row">
				<ul class="col-xs-12">
					<li{% if request.resolver_match.url_name == 'index' %} class="active"{% endif %}><a href="{% url 'index' %}">Главная</a></li>
					<li{% if request.resolver_match.url_name == 'download' %} class="active"{% endif %}><a href="{% url 'download' %}">Скачать</a></li>
					<li{% if request.resolver_match.url_name == 'gallery' %} class="active"{% endif %}><a href="{% url 'gallery' %}">Галерея</a></li>
					<li{% if request.resolver_match.url_name == 'help' %} class="active"{% endif %} class="disabled">{#<a href="{% url 'help' %}">#}Справка{#</a>#}</li>
					<li{% if request.resolver_match.url_name == 'feedback' %} class="active"{% endif %}><a href="{% url 'feedback' %}">Написать</a></li>
				</ul>
			</nav>
		</header>
		<div class="main">
			{% block main %}
			{% endblock %}
		</div>
	</div>
	<div class="container">
		<footer class="page-footer row">
				<p class="col-xs-3 copyright">Gvis &#64; 2015</p>
				<p class="col-xs-9 author">Каретный Роман, кафедра ЮНЕСКО по ИВТ</p>
		</footer>
	</div>
	<script src="http://yastatic.net/jquery/1.11.2/jquery.min.js"></script>
	{% compress js %}
		<script src="{% static 'pages/js/script.js' %}"></script>
	{% endcompress %}
</body>
</html>

pages/templates/pages/download.html
{% extends 'pages/base.html' %}
{% load page_tags %}

{% block title %}Загрузки - {{ block.super }}{% endblock %}

{% block main %}
<div class="row download">
    {% with count=5 %}
        <div class="col-sm-5 links-wrap">
            <h3>Windows</h3>
            {% download_links 'WIN' count %}
        </div>
        <div class="col-sm-5 col-sm-offset-2 links-wrap">
            <h3>Linux</h3>
            {% download_links 'LIN' count %}
        </div>
    {% endwith %}
</div>
<p><a href="https://yadi.sk/d/-07mtXczjSM2V">Входные данные</a></p>
{% endblock %}

pages/templates/pages/gallery.html
{% extends 'pages/base.html' %}

{% block title %}Галерея - {{ block.super }}{% endblock %}

{% block main %}
{% if examples %}
    {% for example in examples %}
        <div class="example">
            <h3 class="title">{{ example.title }}</h3>
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/{{ example.video_id }}?autohide=1&loop=1&playlist={{ example.video_id }}&rel=0&showinfo=0"
                    frameborder="0" allowfullscreen>
            </iframe>
            <p class="description">{{ example.description }}</p>
            <a href="{{ example.data_url }}">Скачать данные</a>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

pages/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}

{% block main %}
<img class="app-img" alt="" width="710" height="377" src="{% static 'pages/img/gvis-cavity.jpg' %}">
<div class="row">
    <button class="btn btn-download"><a href="{% url 'download' %}">Скачать</a></button>
</div>
{% endblock %}

pages/templates/pages/links_list.html
{% if gvis_links %}

    {% for link in gvis_links %}
            <div class="link">
                <a href="{{ link.download_url }}">Gvis-{{ link.get_os_type_display }}-{{ link.get_version }}</a>
                <div class="info">
                        <div class="toggle">
                            <span>Информация о выпуске</span>
                            <span class="toggle-text">(показать)</span>
                        </div>
                        <div class="details">{{ link.version_description|safe }}</div>
                    </div>
            </div>

    {% endfor %}
{% else %}
    <li><p>Скоро</p></li>
{% endif %}